server:
  port: 8101

spring:
  application:
    name: cloud-provider-hystrix-payment8101


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: hystrix-payment8101