server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 331224
  #配置config
  cloud:
    #server 配置
    config:
      server:
        git:
          uri: https://github.com/fanda521/spring-cloud-config-study.git #自己github仓库的地址
          search-paths:
            - springcloud-config
          #uri: git@github:com:fanda521/spring-cloud-config-study.git
      label: master #仓库的分支名

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    prefer-ip-address: true
    instance-id: cloud-config-center3344

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5627
  username: guest
  password: guest

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"




