server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #配置网关
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
# 写死的地址
#      routes:
#        - id: payment_routh #payment_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/** #断言，路径相匹配的进行路由
#
#        - id: payment_routh2 #payment_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb/** #断言，路径相匹配的进行路由
      #动态的地址，负载均衡，通过为服务名
      routes:
        - id: payment_routh #payment_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri : lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
#            - After=2021-01-16T16:23:41.825+08:00[Asia/Shanghai] #某个时间后才能有效
#            - Cookie=username,zzyy #必须带cookie才能生效  curl http://localhost:9527/payment/lb --cookie "username=zzyy"
#            - Header=X-Request-Id, \d+ #请求头要有  X-Request-Id属性并且值为整数，curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:1234"

eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
    instance-id: cloud-gateway-service9527

  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
